### ISSUE TITLE
WIDERFACE_train   predict_error

### ISSUE THREAD

**Issue by babyblue1334** [YonghaoHe/Light-And-Fast-Object-Detectors#44]
WIDERFACE_train

lib_path: F:\Desktop\LFD-A-Light-and-Fast-Detector-master\lfd\data_pipeline\dataset\utils\libs
libturtojpeg_path_list: []
Traceback (most recent call last):
  File "F:/Desktop/LFD-A-Light-and-Fast-Detector-master/WIDERFACE_train/predict.py", line 4, in <module>
    from lfd.data_pipeline.augmentation import *
  File "F:\Desktop\LFD-A-Light-and-Fast-Detector-master\lfd\data_pipeline\__init__.py", line 4, in <module>
    from .data_loader import *
  File "F:\Desktop\LFD-A-Light-and-Fast-Detector-master\lfd\data_pipeline\data_loader\__init__.py", line 3, in <module>
    from .data_loader import DataLoader
  File "F:\Desktop\LFD-A-Light-and-Fast-Detector-master\lfd\data_pipeline\data_loader\data_loader.py", line 8, in <module>
    from ..dataset import turbojpeg, reserved_keys
  File "F:\Desktop\LFD-A-Light-and-Fast-Detector-master\lfd\data_pipeline\dataset\__init__.py", line 7, in <module>
    from .utils import *
  File "F:\Desktop\LFD-A-Light-and-Fast-Detector-master\lfd\data_pipeline\dataset\utils\__init__.py", line 3, in <module>
    from .turbojpeg import turbojpeg
  File "F:\Desktop\LFD-A-Light-and-Fast-Detector-master\lfd\data_pipeline\dataset\utils\turbojpeg.py", line 457, in <module>
    target_libturbojpeg_path = max(libturtojpeg_path_list)
ValueError: max() arg is an empty sequence

Process finished with exit code 1

**Comment by YonghaoHe** [comment]
@babyblue1334 In Windows, the name of libturbojpeg has the suffix of .dll , not .so in Linux.
